# Browser configuration
browser:
  headless: true
  use_test_profile: true
  test_profile_name: "test_profile"
  extra_browser_args:
    - "--disable-blink-features=AutomationControlled"

# Browser context configuration
context:
  disable_security: true
  cookies_file: "auth_data/test_profile/cookies.json"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  permissions:
    - "clipboard-read"
    - "clipboard-write"
  # Set allowed_domains to None to allow all domains
  # You can use any of these formats:
  allowed_domains: null  # YAML null
  # 
  # Or set specific domains:
  # allowed_domains:
  #   - "amazon.com"
  #   - "google.com"
  #   - "github.com"
  #   - "huggingface.co"
  #   - "outlook.com"

# LLM configuration
llm:
  # Choose your provider: "openai" or "anthropic"
  provider: "openai"
  model: "gpt-4o"
  temperature: 0.7  # Controls randomness in responses (0.0 = deterministic, 1.0 = creative)
  max_tokens: null  # Maximum tokens in response (null = use model default)
  
  # OpenAI examples:
  # provider: "openai"
  # model: "gpt-4o"              # Latest GPT-4 Omni
  # model: "gpt-4o-mini"         # Smaller, faster GPT-4 Omni
  # model: "gpt-4-turbo"         # GPT-4 Turbo
  
  # Anthropic examples:
  # provider: "anthropic"
  # model: "claude-3-7-sonnet-20250219"  # Latest Claude 3.7 Sonnet
  # model: "claude-3-5-haiku-20241022"   # Claude 3.5 Haiku (faster)
  # model: "claude-3-opus-20240229"      # Claude 3 Opus (most capable)

# Task configuration
tasks_file: "tasks_test.txt"
batch_size: 5

# Agent configuration
agent:
  max_steps: 50        # Maximum number of steps the agent will take per task
  max_failures: 3         # Maximum consecutive failures before stopping
  retry_delay: 10         # Delay in seconds between retries after failures
  use_vision: true        # Enable screenshot analysis
  enable_memory: true     # Enable long-term memory
  max_actions_per_step: 10 # Maximum actions the agent can take in a single step

# Authentication management configuration
auth_manager:
  ensure_logged_in: false # Whether to automatically login to services (Google, etc.)
  save_auth_state: false  # Whether to save authentication state between runs